void solv_top_dil(const TLorentzVector & l1,
		  const TLorentzVector & l2,
		  const TLorentzVector & b1,
		  const TLorentzVector & b2,
		  double metx,
		  double mety,
		  TLorentzVector (&n1)[4],
		  TLorentzVector (&n2)[4],
		  int &n,
		  double mt, double mw, double mb);


void solv_top_dil_img(const TLorentzVector & l1,
		      const TLorentzVector & l2,
		      const TLorentzVector & b1,
		      const TLorentzVector & b2,
		      double metx,
		      double mety,
		      TLorentzVector (&n1)[4],
		      TLorentzVector (&n2)[4],
		      int &n,
		      double mt, double mw, double mb,
		      TLorentzVector (&ipnu1)[4], TLorentzVector (&ipnu2)[4]);

void solv_top_lj(const TLorentzVector & l1,
		 const TLorentzVector & b1,
		 const TLorentzVector & b2,
		 const TLorentzVector & j1,
		 const TLorentzVector & j2,
		 double metx,
		 double mety,
		 double mt, double mw, double mb,
		 TLorentzVector &fit_l1,
		 TLorentzVector &fit_n1,
		 TLorentzVector &fit_b1,
		 TLorentzVector &fit_b2,
		 TLorentzVector &fit_j1,
		 TLorentzVector &fit_j2,
		 double &chi2);
